### ISSUE TITLE
add a console per network

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#1640]
*Issue migrated from trac ticket [#1419](http://colloquy.info/project/ticket/1419)*

**type:** Enhancement | **component:** Colloquy (iOS) | **severity:** Critical | **priority:** Highest | **version:** 1.0 (iOS) | **status:** accepted
___
#### 2009-01-20 05:35:36: @janeylicious created the issue

self explanatory
___
#### 2009-03-14 01:42:04: @janeylicious changed priority from *High* to *Highest*

___
#### 2009-03-14 01:42:04: @janeylicious changed severity from *Normal* to *Critical*

___
#### 2009-03-14 01:42:04: @janeylicious commented

so like, this would come in handy for troubleshooting. i wonder how to go about displaying it though.

___
#### 2009-03-14 01:42:54: @akempgen commented

also a way to paste this into the support room would be helpful

___
#### 2009-07-11 07:35:11: @xeenon changed status from *new* to *accepted*

___
#### 2009-08-30 03:40:02: lazybones commented

I would have it slide down from the title/button bar by tapping on the channel name if you are in a channel.

From the connections list it could be added to the Disconnect, Cancel list when you tap on the channel.. In addition on this screen the last two lines of console messages could be displayed like the last two messages are on the Colloquies list.

**Comment by zadr** [comment]
we have a console, and have for awhile
