### ISSUE TITLE
Colloquy fails to include trailing ) in links

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#1837]
*Issue migrated from trac ticket [#1624](http://colloquy.info/project/ticket/1624)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **priority:** Normal | **version:** 2.2 (Mac) | **status:** new
___
#### 2009-06-01 11:32:09: macdome created the issue

Colloquy fails to include trailing ) in links

Example link:
http://build.chromium.org/buildbot/waterfall.fyi/waterfall?builder=Webkit%20(webkit.org)

Google's linker gets it right:
http://code.google.com/p/chromium/issues/detail?id=13058
___
#### 2009-06-01 11:36:25: Catfish_Man commented

http://trac.adium.im/wiki/AutoHyperlinksFramework (BSD licensed) could be useful for this

**Comment by zadr** [comment]
This is fixed, at least in 2.5 beta builds!
