### ISSUE TITLE
http://tinyarro.ws/ shortlinks aren't clickable

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#1891]
*Issue migrated from trac ticket [#1678](http://colloquy.info/project/ticket/1678)*

**type:** Enhancement | **component:** Colloquy (Mac) | **severity:** Minor | **priority:** Normal | **version:** 2.2 (Mac) | **status:** new
___
#### 2009-07-18 15:25:48: Hendrik.Beskow@… created the issue

Hello!
The shortlinks created by http://tinyarro.ws/ aren't clickable, at least some of them.
Would really appreciate it when you could "fix" that :)

Greetings,
Hendrik Beskow

**Comment by zadr** [comment]
resolved by 3044920dde944dbcddcb803d8c5bb690619ac6f9!
