### ISSUE TITLE
Mobile Transcripts

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#2247]
*Issue migrated from trac ticket [#2045](http://colloquy.info/project/ticket/2045)*

**type:** Enhancement | **component:** Colloquy (iOS) | **severity:** Trivial | **priority:** Low | **version:** 1.1 (iOS) | **status:** assigned | **keywords:** transcripts, sync, OTA
___
#### 2010-03-21 08:43:33: CaptainKirk created the issue

Colloquy iPhone should also support transcripts and should have an option to sync them OTA with a Mac's Transcripts folder.
___
#### 2010-03-22 05:21:15: @zadr changed status from *new* to *assigned*

___
#### 2010-03-22 05:21:15: @zadr changed owner from *kiji.roshi* to *zach*

___
#### 2010-03-22 05:21:15: @zadr commented

Mobile Colloquy should be able to email the current buffer to you for saving/viewing later. Syncing with Mac for transcripts is much less likely to happen.

**Comment by zadr** [comment]
Saving the current transcript is possible now
