### ISSUE TITLE
Colloquy Buddy list question

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#2619]
*Issue migrated from trac ticket [#2573](http://colloquy.info/project/ticket/2573)*

**type:** Enhancement | **component:** Colloquy (Mac) | **severity:** Normal | **priority:** Normal | **version:** 2.3 (Mac) | **status:** new | **keywords:** Buddy List
___
#### 2011-02-25 20:06:05: jamie.mellor@… created the issue

Is it possible to have your buddy list update when one of your friends logs off IRC, and they're not in the same room as you?

Currently it only updates when you either type something to that person, or do a whois/Get Info, but clients such as mIRC on the PC update their notify lists automatically

**Comment by zadr** [comment]
This should work now with `ISON` and `WATCH` support
