### ISSUE TITLE
Colloquy users autojoin

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#2788]
*Issue migrated from trac ticket [#2852](http://colloquy.info/project/ticket/2852)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Critical | **priority:** High | **status:** new
___
#### 2011-09-23 21:11:24: slangirc@… created the issue

Hello, I'm here from a help channel at Undernet (#Help), a channel which have been visited many times by Colloquy users. When asked, those users have no idea of being in that channel, as if they were auto-joining that channel without even noticing. I personally don't use your products, and have not been able to speak with someone that is using your products. However, I have tried to explain this situation to someone in #colloquy-mobile @ Freenode but everyone was idling every time I was in there. Please, with your help, I would like to know if this is a feature that your product has.I am aware this is a bit of a stretch to ask you this, but it will be very helpful if this "problem" would be explained.
With pleasure,
slang @ Undernet (slangirc@gmail.com)

**Comment by zadr** [comment]
e2fda18b9c87331ac0c5dd5725f32e5a36d9be39 addressed this
