### ISSUE TITLE
Add option to allow ignoring "joined" and "left" messages?

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#2935]
*Issue migrated from trac ticket [#3159](http://colloquy.info/project/ticket/3159)*

**type:** Enhancement | **component:** Colloquy (Mac) | **severity:** Normal | **priority:** Normal | **version:** 2.3 (Mac) | **status:** closed | **resolution:** Works for Me
___
#### 2012-06-02 10:55:42: anonymous created the issue

___
#### 2012-10-14 23:21:07: @zadr changed status from *new* to *closed*

___
#### 2012-10-14 23:21:07: @zadr changed resolution from ** to *Works for Me*

___
#### 2012-10-14 23:21:07: @zadr commented

http://colloquy.info/project/wiki/FAQs#Doescolloquyhaveawaytoignorehidepartsnicksetcinabusyroom

**Comment by cobber** [comment]
Hi,

I just downloaded the 2.5-prerelease-7097 and also wanted to "filter out" member joined/left messaged.

The FAQ link from @zadr seems to have gone away and I can't see an obvious solution.
My expectation would have been a `[ ] hide messages` option in the alerts preferences pane... in addition to the `[ ] Play sound`, `[ ] bounce Colloquy icon in the Dock` and `[ ] Show event bubble` options for specific events.

Any help would be greatly appreciated, or should I open a new issue?

**Comment by akempgen** [comment]
The solution is to create a new style variant (Colloquy Preferences > Styles > Configure …). This will create a CSS file in ~/Library/Application Support/Colloquy/Styles/Variants. Edit that file, and put something like
```
.event {
    display: none;
}
```
inside. Not super convenient, but it works, and you can switch between the normal style and your "no events" variant as a per room setting.

**Comment by cobber** [comment]
Hi,

thanks - it works, with a few tweaks.... but... ouch!
can we please re-open this issue and add a button to the UI?

Tweaks for 2.5-prerelease-7097:
- Colloquy > Preferences > ***Appearance*** > Default Style > [Customize Style]
  - or via the *[Style] > Appearance Preferences* button menu from the main chat window
- the empty css file was at `~/Library/Application\ Support/Colloquy/Styles/Variants/cc.javelin.colloquy.style.standard/no\ events.css`
- I had to quit Colloquy, then edit the css file, then start colloquy again
  - when I edited the file while Colloquy was running and then quit Colloquy, the file was empty again - no idea why
- the room I was in didn't magically change styles
  - manually select the new style via the *[Style] > Standard > no events* button-menu on the main window

`.event { display: none; }` works fine, but are other CSS classes used by Colloquy documented anywhere? (for the curious)

Cheers and thanks for the helpful reply!
