### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3131]
*Issue migrated from trac ticket [#3457](http://colloquy.info/project/ticket/3457)*

**type:** Defect | **component:** Web Site | **severity:** Major | **status:** new | **keywords:** Error, 500, Ticket
___
#### 2013-01-23 11:41:57: helin0x99@… created the issue

Getting a server Error 500 when submitting a ticket. 

Does appear to go however as its appearing on activity!
___
#### 2013-05-13 08:30:56: anonymous commented

I'm still seeing that error

**Comment by zadr** [comment]
we migrated to GitHub for issue tracking
