### ISSUE TITLE
Mobile App doesn't display log

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3159]
*Issue migrated from trac ticket [#3492](http://colloquy.info/project/ticket/3492)*

**type:** Defect | **component:** Colloquy (Bouncer) | **severity:** Major | **version:** 2.4 (Mac) | **status:** new
___
#### 2013-02-24 22:38:45: julien.dupeyron@… created the issue

I don't know if the problem comes from new iOS app or latest osx update, but when I log in the bouncer it doesn't display all the activity happened in the channels... I loved how colloquy mobile resume all discussions when I connected with iPad/iPhone but it doesn't anymore :(
___
#### 2013-02-25 10:55:41: lapypool@… commented

I'm using colloquy iOS on iphone, ipad and colloquy OSX
Got a lot of trouble since the latest version : 
- When I write on a channel with ios app and then I look at what I typed on my mac, sometimes it's displayed, sometimes it's not.
- OSX app showing every single time I connect thru the bouncer in Preference/bouncer menu. If I connect/disconnect 15 times it shows "15 clients connected, 4 connections available to bounce"
- iOS app doesn't display history when I reconnect.

___
#### 2013-03-02 11:15:21: anonymous commented

I switched back on 2.4 (5436), log are back, everything works like it should. Hope you'll find the problem !

___
#### 2013-03-02 13:27:08: @zadr commented

Weird. Thanks for confirming that it works in 2.4 and not 2.4.1. Will have to look into this.

___
#### 2013-03-21 19:24:19: anonymous commented

Thanks. I was  experiencing the same issues. I went back to 2.4 and all is well.

___
#### 2013-05-24 10:50:35: anonymous commented

2.4.2 still have the bug :(

___
#### 2013-05-24 15:00:12: anonymous commented

Yep, back to 2.4   :(

___
#### 2014-03-22 09:04:16: anonymous commented

Is 2.4.3 fixing the bug ?

___
#### 2014-03-22 11:16:52: anonymous commented

it's not :(((( back to 2.4 once again...

___
#### 2014-03-25 23:59:18: anonymous commented

it's back to 2.4  :(

___
#### 2014-05-23 20:46:30: julien.dupeyron@… commented

Hi can we expect this bug will be fixed one day  ??
My iOS app is useless without the bouncer working :(((

___
#### 2014-06-16 19:16:17: anonymous commented

I also have this problem

___
#### 2014-11-17 22:49:40: anonymous commented

Waiting the next update expecting this bug to be resolved. Please !

**Comment by zadr** [comment]
there were issues with the bouncer that have since been resolved
