### ISSUE TITLE
Chat messages randomly not showing

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3302]
*Issue migrated from trac ticket [#4032](http://colloquy.info/project/ticket/4032)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Major | **version:** 2.4 (Mac) | **status:** new
___
#### 2013-11-10 12:12:42: anonymous created the issue

Since update the client is hella buggy.

Some times my messages and other people messages dont show up until I change the style of the client (flat bubble etc)

**Comment by zadr** [comment]
caused by the same thing that causes https://github.com/colloquy/colloquy/issues/3194
