### ISSUE TITLE
Messages not going to channel

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3460]
*Issue migrated from trac ticket [#4429](http://colloquy.info/project/ticket/4429)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Blocker | **version:** 1.6 (iOS) | **status:** closed | **resolution:** Fixed
___
#### 2014-12-18 19:01:17: lstrong@… created the issue

v1.6.1 and 1.6.2.  When I first join a channel my first message or two go through but stop after that.  When I look at the console tab I see:
"@account=myaccount PRIVMSG #mychannel blah blah blah"  

followed by:
"421 MyNick @account=myaccount Unknown command"

Other people in the channel don't receive my messages.

I'm using dircproxy 1.05 as a bouncer in case that makes a difference.  I haven't had any issues until the upgrade to 1.6.1

In the meantime I've had to downgrade.
___
#### 2014-12-18 19:54:33: anonymous commented

Apologies for the multiple tickets  (the ticket creator is throwing a 500)

___
#### 2014-12-19 20:53:24: @zadr changed status from *new* to *closed*

___
#### 2014-12-19 20:53:24: @zadr changed resolution from ** to *Fixed*

___
#### 2014-12-19 20:53:24: @zadr commented

fixed in d35f9ca926e011d8e652fec2f8422fd2147a4eca, update has been submitted to Apple.

**Comment by Veroni-i** [comment]
I observe this behavior in mac/2020/2.5-prerelease-7051 which was released after this was supposed to be fixed.
Happens immediately after I join a channel.
Using MacOS Big Sur.
