### ISSUE TITLE
Support for the playback module (http://wiki.znc.in/Playback) doesn't work

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3474]
*Issue migrated from trac ticket [#4450](http://colloquy.info/project/ticket/4450)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Normal | **status:** closed | **resolution:** Fixed
___
#### 2015-01-04 12:26:51: foldericon@… created the issue

It doesn't show any lines from the buffer when connecting to a ZNC with playback module. My wild guess is that it just sends the current timestamp instead of the one from the last received message. 
___
#### 2015-01-07 09:39:57: @zadr changed status from *new* to *closed*

___
#### 2015-01-07 09:39:57: @zadr changed resolution from ** to *Fixed*

**Comment by christopherredden** [comment]
Was this actually fixed? Colloquy is listed as supporting this module on the ZNC wiki, but it just doesn't work at all.

**Comment by zadr** [comment]
@christopherredden `*playback` support was first introduced in b6509d36315082f954a92eaff8c22468f758fd7a back in January 2015 and last touched in be7a2812a0841723558d5bf61bf67f2ffd343395 which landed on April 2016.

It is possible that in the past 4.5 years, something has changed with the `*playback` module that has caused things to break.
