### ISSUE TITLE
Odd pauses and stalls, with errors listed in system console

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3496]
*Issue migrated from trac ticket [#4493](http://colloquy.info/project/ticket/4493)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new | **keywords:** pause, console errors
___
#### 2015-06-01 18:20:44: jhod@… created the issue

Hi there. Just started using Colloquy again after a long time away, and ran into some very strange errors. Here's what showed up in the system console:

  6/1/15 10:08:43.510 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fbce7f70 </Applications/Colloquy.app/Contents/Resources/Styles/Bland.colloquyStyle> (not loaded)
  6/1/15 10:08:43.511 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5f86c9040 </Applications/Colloquy.app/Contents/Resources/Styles/Bubbles.colloquyStyle> (not loaded)
  6/1/15 10:08:43.512 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fb948010 </Applications/Colloquy.app/Contents/Resources/Styles/DecafBland.colloquyStyle> (not loaded)
  6/1/15 10:08:43.513 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fbcdd1a0 </Applications/Colloquy.app/Contents/Resources/Styles/Fiat.colloquyStyle> (not loaded)
  6/1/15 10:08:43.515 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fbcd62e0 </Applications/Colloquy.app/Contents/Resources/Styles/Novel.colloquyStyle> (not loaded)
  6/1/15 10:08:43.516 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fbcc3d20 </Applications/Colloquy.app/Contents/Resources/Styles/Standard.colloquyStyle> (not loaded)
  6/1/15 10:08:43.517 AM Colloquy17079: Cannot find executable for CFBundle 0x7fe5fbcbf030 </Applications/Colloquy.app/Contents/Resources/Styles/Synapse.colloquyStyle> (not loaded)
  6/1/15 10:08:48.723 AM WindowServer0daae53e290d0634b4086eaf702c2ba0c0c87a8a: disable_update_timeout: UI updates were forcibly disabled by application "Colloquy" for over 1.00 seconds. Server has re-enabled them.
  6/1/15 10:08:56.761 AM Colloquy17079: IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_overrideKeyboardWithKeyboardNamed:reply:) block performed very slowly (3.30 secs)
  6/1/15 10:09:00.951 AM Colloquy17079: IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_overrideKeyboardWithKeyboardNamed:reply:) block performed very slowly (4.19 secs)
  6/1/15 10:09:02.724 AM WindowServer0daae53e290d0634b4086eaf702c2ba0c0c87a8a: disable_update_likely_unbalanced: UI updates still disabled by application "Colloquy" after 15.00 seconds (server forcibly re-enabled them after 1.00 seconds). Likely an unbalanced disableUpdate call.
  6/1/15 10:09:07.790 AM Colloquy17079: IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_isIncrementalSearchInputContextWithReply:) block performed very slowly (11.03 secs)
  6/1/15 10:09:07.790 AM Colloquy17079: IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_incrementalSearchClientGeometryWithReply:) block performed very slowly (6.84 secs)
  6/1/15 10:09:07.790 AM Colloquy17079: IMK Stall detected, *please Report* your user scenario in <rdar://problem/16792073> - (invocationInterruptXPCReply) block performed very slowly (6.84 secs)
  6/1/15 10:09:18.721 AM WindowServer0daae53e290d0634b4086eaf702c2ba0c0c87a8a: common_reenable_update: UI updates were finally reenabled by application "Colloquy" after 31.00 seconds (server forcibly re-enabled them after 1.00 seconds)
  6/1/15 10:09:19.218 AM Colloquy17079: void CGSUpdateManager::log() const: conn 0x52ae7: spurious update.

Colloquy seems to work, but there are some odd pauses while typing, or waiting for IRC rooms to open, etc.  I'm using Colloquy 2.4.3 on MacOS 10.10.4 (14E26a)

**Comment by zadr** [comment]
dupe of https://github.com/colloquy/colloquy/issues/662
