### ISSUE TITLE
IRC: Smiley image for :p displayed twice if a user named "p" is in the channel

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3514]
*Issue migrated from trac ticket [#4544](http://colloquy.info/project/ticket/4544)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new | **keywords:** irc smiley
___
#### 2015-08-15 00:44:48: durka42+colloquy@… created the issue

Colloquy replaces the literal text ":p" with the tongue-sticking-out smiley. If there is a user in the channel named "p", it attempts to display a link to start a chat with that user. This somehow results in the smiley image being doubled (the second one is the link).

**Comment by zadr** [comment]
fixed by 179dcfd525a8feb1c33823b452e6bd8730887bc5
