### ISSUE TITLE
Colloquy causing mac to freeze & crash

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3573]
*Issue migrated from trac ticket [#4639](http://colloquy.info/project/ticket/4639)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2015-12-19 01:57:11: anonymous created the issue

Each time I've started up Colloquy and it gets to where I can get into the chat, it starts to slow my computer down and then freezes. How do I fix this??

**Comment by zadr** [comment]
dupe of https://github.com/colloquy/colloquy/issues/662
