### ISSUE TITLE
Person's text is not displaying

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3583]
*Issue migrated from trac ticket [#4649](http://colloquy.info/project/ticket/4649)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-01-20 22:26:46: SnipersLaww@… created the issue

In atleast one of my channels since I have noticed.. out of nowhere (no modifications to the system on either his end or my end).. anything he says isnt being displayed in chat.  not even in direct messages.  I know I am receiving data from him because I tested with other clients and a bot I run off of my machine also receives his messages.  This just started the other day and I havent been able to see any of his text ever since with the colloquy client.  He is not being ignored nor is he on any list.  This issue has made me also wonder how many other people could possibly be talking and I also never noticed because I wasnt paying close enough attention to see interactions with them.  I ran the console and it does show him speaking in there.. but just not in the channel and private messages.  The chat counter also goes up when they speak.  I have even tried changing styles and reloading the style like I have seen in another report but no fix.
___
#### 2016-02-13 09:05:25: anonymous commented

Can you share what server this is happening on? Or if the person's nick has any special characters in it?

**Comment by zadr** [comment]
caused by the same thing that causes https://github.com/colloquy/colloquy/issues/3194
