### ISSUE TITLE
Text hidden behind input field again / didn't fix offline issue

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3600]
*Issue migrated from trac ticket [#4890](http://colloquy.info/project/ticket/4890)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Normal | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-04-15 13:34:30: anonymous created the issue

The old bug with text hidden behind the input field is back, plus you still get the erroneous 'offline' status even for users who are still online.  Updates do not appear to be tested prior to being released.   Version 1.8.5 was good, everything since has gotten worse and worse.  This is for colloquy iOS.
___
#### 2016-04-16 23:43:09: @zadr changed version from *2.4 (Mac)* to *1.8 (iOS)*

___
#### 2016-04-16 23:43:09: @zadr changed component from *Chat Core (IRC)* to *Colloquy (iOS)*

___
#### 2016-04-16 23:43:09: @zadr edited the issue description

**Comment by zadr** [comment]
a2e8e7eea94fa30e6392251add69ca5974982ced will help with this
