### ISSUE TITLE
Nickname changes sometimes don't appear

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3602]
*Issue migrated from trac ticket [#4892](http://colloquy.info/project/ticket/4892)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** Local Build | **status:** new
___
#### 2016-04-20 03:44:49: Scaredy created the issue

In SVN build 6780, occasionally nickname changes don't appear in channel, and the channel nick list does not get updated. It's not consistent and I haven't been able to identify any particular pattern. Others have reported this issue in IRC as well.

**Comment by zadr** [comment]
caused by the same thing that causes https://github.com/colloquy/colloquy/issues/3194
