### ISSUE TITLE
Keyboard hides messages

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3616]
*Issue migrated from trac ticket [#5245](http://colloquy.info/project/ticket/5245)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Normal | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-06-24 15:22:51: anonymous created the issue

I am using latest version in ios 8 and since the last update when I send or receive a message the keyboard hides it and I have to scroll it.0

**Comment by zadr** [comment]
a2e8e7eea94fa30e6392251add69ca5974982ced will help with this
