### ISSUE TITLE
Online status in user info is consistently incorrect

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3618]
*Issue migrated from trac ticket [#5629](http://colloquy.info/project/ticket/5629)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Trivial | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-07-19 18:18:58: AdamTheChespin created the issue

Many user info windows report that the user is offline when in reality they are online. This bug causes the private message function to largely be unusable in sending replies. Private message function does work for incoming messages though.
___
#### 2016-07-19 18:29:34: kantlivelong@… commented

I am also seeing this issue. Sending with /msg from another window works fine.

**Comment by zadr** [comment]
this should be fixed in 1.8.11, coming in the next few days
