### ISSUE TITLE
Push Notification Requests Should Receive Acknowledgement

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3619]
*Issue migrated from trac ticket [#5682](http://colloquy.info/project/ticket/5682)*

**type:** Enhancement | **component:** Colloquy (iOS) | **severity:** Minor | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-07-20 02:08:57: kantlivelong@… created the issue

Clients sending a push notification to colloquy.mobi:7906 should receive an acknowledgement when request is successfully processed.

**Comment by zadr** [comment]
Moving the bouncer over to the http2 api instead of the old binary api will make this easy to fix

**Comment by zadr** [comment]
the push server will now write a response back with information about success or failures. In the case of an APNS failure, we will send the underlying status code and response reason back from Apple, as documented (also by Apple) in https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html
