### ISSUE TITLE
No way to set "real name"

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3620]
*Issue migrated from trac ticket [#5683](http://colloquy.info/project/ticket/5683)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-07-20 19:30:14: anonymous created the issue

I can't find any place to set the "real name" or default user name.

**Comment by zadr** [comment]
If you open the Connections window and change your real name or username in any textfield, the new value is applied as the new default to pre-fill the next time a connection is created.
