### ISSUE TITLE
Colloquy force discrete GPU

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3622]
*Issue migrated from trac ticket [#6029](http://colloquy.info/project/ticket/6029)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Major | **version:** 2.4 (Mac) | **status:** new | **keywords:** GPU discrete switch
___
#### 2016-07-28 14:01:27: godzil@… created the issue

On Mac OS X Sierra at least, running Colloquy 2.4.3 for the system to use the discrete graphc card which is quite bad for autonomy. I'm not 100% sure if it was the case on older version of OS X, but it happen 100% of the time on 10.12.

I've tested to add the "NSSupportsAutomaticGraphicsSwitching" parameter to true in the main Info.plist, and solved the issue here. I think it would be worth to add that parameter by default, there is no drawback, i don't thing that Colloquy really need the use of the discrete GPU card!

**Comment by zadr** [comment]
done! bbe5bf10
