### ISSUE TITLE
Connection issues to colloquy.mobi:7909

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3624]
*Issue migrated from trac ticket [#6147](http://colloquy.info/project/ticket/6147)*

**type:** Defect | **component:** Colloquy (Bouncer) | **severity:** Normal | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-08-02 13:08:59: roman.rennhofer@… created the issue

Hello!

I use a ZNC bouncer with the colloquy Modul. The Push Notification worked perfekt for at least 4 months. But suddenly the Push Notifications stopped working. 

I exectued the command "openssl s_client -connect colloquy.mobi:7906 -tls1_2" and it seems like it doesn't work:

"
CONNECTED(00000003)
6280832:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1470135976
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
"
It seems like i got blocked or something. My IP is 213.47.34.4 could you please verify the issue and tell me what went wrong?

Thanks in advance
Roman

**Comment by zadr** [comment]
closing old bouncer connectivity issues
