### ISSUE TITLE
No chat reaction to text box selection; hides half of chat and text box

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3626]
*Issue migrated from trac ticket [#7028](http://colloquy.info/project/ticket/7028)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Major | **version:** 1.8 (iOS) | **status:** new
___
#### 2016-08-17 05:27:57: anonymous created the issue

The latest update for the mobile app does not react to selecting the text box, and hides both the text box and several previous messages. It is impossible to see what is being typed and several of the latest lines without deselecting the text box.

**Comment by zadr** [comment]
bce54b6252736e1dc5ec6ea8882f40362698c11c will help with this
