### ISSUE TITLE
Hang on reconnect if using an IRC bouncer

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3627]
*Issue migrated from trac ticket [#8270](http://colloquy.info/project/ticket/8270)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Major | **version:** 2.4 (Mac) | **status:** new | **keywords:** bouncer, IRC, reconnect
___
#### 2016-09-21 15:19:40: paulisaacsd@… created the issue

I'm using IRC bouncers (the ones provided by the IRCs themselves) and I have it formatted to work properly with Colloquy. When I connect for the first time, the bouncers send their playbacks (up to 499 messages on replay) normally. However, if I disconnect, then reconnect the bouncers after enough time (typically a day, because sleep mode), the sheer size of the replays hangs Colloquy, forcing a restart, which then means I lose the replay. I would like to actually see the replays and not have to restart Colloquy and lose them all...

**Comment by zadr** [comment]
dupe of https://github.com/colloquy/colloquy/issues/662
