### ISSUE TITLE
CQKeychain setPassword: doesn't set display name

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3630]
*Issue migrated from trac ticket [#8383](http://colloquy.info/project/ticket/8383)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-10-06 20:38:59: @MaddTheSane created the issue

CQKeychain setPassword:forServer:area:displayValue: does not call setData:forServer:area:displayValue:, making any passed in display values lost and leaving nonsense keychain entries like "POK3ADM0PJ5".

**Comment by zadr** [comment]
fixed in 4cb12c047ea8c4e9e9dbc09a862c99128e1567a1
