### ISSUE TITLE
why is there no undernet server

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3631]
*Issue migrated from trac ticket [#9066](http://colloquy.info/project/ticket/9066)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-10-19 02:19:31: anonymous created the issue

i have previous colloquy and it has undernet server, why is it the new one that i purchased doeant have undernet server? tnx

**Comment by zadr** [comment]
Undernet is still in the list of servers suggested by Colloquy
