### ISSUE TITLE
telent to push server  immediately terminates

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3632]
*Issue migrated from trac ticket [#9068](http://colloquy.info/project/ticket/9068)*

**type:** Defect | **component:** Colloquy (Bouncer) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-10-20 19:45:54: colloquy@… created the issue

telnet colloquy.mobi 7906 results in an instant termination. How can I find out if my IP address is banned and if so, how can I find out what I did wrong?

**Comment by zadr** [comment]
If telnet is terminating the connection right away, that means the push server will reject all connections from your IP for a short amount of time.

The only reason we reject IP's is if you try to connect over SSLv2 (insecure, unsupported, and clients tend to not upgrade to newer protocols upon rejection) or if your connection keeps timing out without closing the socket.
