### ISSUE TITLE
Message will infrequently be attached to the completely wrong node.

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3634]
*Issue migrated from trac ticket [#9073](http://colloquy.info/project/ticket/9073)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2016-11-30 03:41:31: nashenas88@… created the issue

You can see in the below linked image that my message (in gray) was attached to someone else's message (in not gray) from multiple hours before. It's happened sometimes where I'll send the message, but will notice that my messages weren't sent. I scrolled up today and noticed my message had been joined to another user's thread.

[[Image(http://i.imgur.com/tchOju6.png)]]

**Comment by zadr** [comment]
caused by the same thing that causes https://github.com/colloquy/colloquy/issues/3194
