### ISSUE TITLE
when registering for a specific server i kept getting an error claiming my email was invalid

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3635]
*Issue migrated from trac ticket [#9080](http://colloquy.info/project/ticket/9080)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new | **keywords:** email, registration,
___
#### 2016-12-22 06:36:03: anonymous created the issue

I typed in all of the coms as instructed, and everything should be correct, however whenever I go to execute it says my email is invalid. Any suggestions

**Comment by zadr** [comment]
This is an issue with a specific network (that is not named), not with Colloquy itself, so there's not much we can do.
