### ISSUE TITLE
non riesco a connettermi

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3637]
*Issue migrated from trac ticket [#9089](http://colloquy.info/project/ticket/9089)*

**type:** Defect | **component:** Colloquy (Mac) | **severity:** Normal | **version:** 2.4 (Mac) | **status:** new
___
#### 2017-02-18 19:36:44: mauri.raffi@… created the issue

Per cortesia mi spiegate perché non riesco più a connettermi?
grazie

**Comment by zadr** [comment]
Google Translate says this translates to

```
Please explain why I can not connect?
thank you```

which is not a question we can answer with the info provided.
