### ISSUE TITLE
Annoying initial alert prompts

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3640]
*Issue migrated from trac ticket [#9092](http://colloquy.info/project/ticket/9092)*

**type:** Task | **component:** Colloquy (iOS) | **severity:** Minor | **version:** 1.8 (iOS) | **status:** new | **keywords:** Prompt
___
#### 2017-04-10 22:31:50: CecilWard created the issue

i keep getting two annoying prompts - alert boxes- when I first connect to the service  - I wish I could remember the exact text of the message. I just hit dismiss twice anyway. Any clues?

**Comment by zadr** [comment]
Without knowing the text of the message, there's not much to do.
