### ISSUE TITLE
Doesn't connect over cellular data

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3642]
*Issue migrated from trac ticket [#9096](http://colloquy.info/project/ticket/9096)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Blocker | **version:** 1.8 (iOS) | **status:** new
___
#### 2017-05-07 07:51:47: @darrenoh created the issue

I can connect over wifi, but not over cellular. There are no messages in the console when the connection fails. I have verified that the app is allowed to connect over cellular data.

**Comment by zadr** [comment]
closing this as a migrated issue that doesn't have enough info to debug + is likely an SASL issue
