### ISSUE TITLE
/help command produces a modal dialogbox, then just sits there forever

### ISSUE THREAD

**Issue by akempgen** [colloquy/colloquy#3644]
*Issue migrated from trac ticket [#9111](http://colloquy.info/project/ticket/9111)*

**type:** Defect | **component:** Colloquy (iOS) | **severity:** Normal | **version:** 1.8 (iOS) | **status:** new | **keywords:** help hang ios
___
#### 2017-07-15 01:03:57: janet@… created the issue

After entering the /help command when a modal dialog box appears it says something like updating help and then waits forever. It is cancellable, not a lock-up, probably not a hard thrashing hang. Iirc no internet activity seems to be taking place while this dialog box is sitting there, from looking at stats on an external monitoring system. App and internet connection all fine otherwise.

So no help is available at all.

**Comment by zadr** [comment]
fixed in 762a6e11967b6dbabf212c8998d753d6e1d44196
