### ISSUE TITLE
How to turn off alerting sounds when a member joins a chat room?

### ISSUE THREAD

**Issue by nbro** [colloquy/colloquy#3651]
Go to preferences (<kbd>Cmd</kbd> + <kbd>,</kbd>)

1. Click on the `Alerts tab`
2. Click on the drop-down next to `Chat Event`
3. Change it to `Member Joined Chat Room` and deselect `Play Sound`

Similarly, one may choose to enable or disable alerting sounds for other events by choosing another option at point 2 from the drop-down.

---

**Note:** _this issue was opened only to make [this solution](http://colloquy.info/project/ticket/698) more visible to the public._

**Comment by zadr** [comment]
We appreciate you bringing this up and sharing how Colloquy works, but, an issue tracker is not the best place to share knowledge. Would you consider making a page on our wiki instead? ☺️ https://github.com/colloquy/colloquy/wiki
