### ISSUE TITLE
URLs with unicode characters are unnecessarily prefixed by http://

### ISSUE THREAD

**Issue by readingsnail** [colloquy/colloquy#3653]
Myfriend[4:58pm]:
https://ko.wikipedia.org/wiki/%EB%AC%B5%ED%96%A5_(%EA%B2%8C%EC%9E%84)
Me[4:58pm]: ...

In my Case, this is completed Link, but colloquy is not recognize ) and erase )

using 2.5 r6011 + bouncer 71

~~also sorry, but bug report in collouqy menu is broken~~

~~Error: Forbidden~~

~~TICKET_CREATE privileges are required to perform this operation. You don't have the required permissions.~~

**Comment by akempgen** [comment]
Thanks for the report, i moved the part about the menu item into its own issue.

**Comment by akempgen** [comment]
btw, there is a newer 2.5 preview available if you stop by in our support room

**Comment by readingsnail** [comment]
and some affect of nightly (in IRC Channel Release version), People pasted link like this - http://www.https.com//ko.wikipedia.org/wiki/blahblah - paste link is https://ko.wikipedia.org/wiki/blahblah

**Comment by akempgen** [comment]
this affects urls with unicode characters in the domain or path, caused by this bug in NSURL http://www.openradar.me/6923664. let's see if we can work around it …

**Comment by akempgen** [comment]
@readingsnail i made a new prerelease build with this fix
