### ISSUE TITLE
Prompt for a password on start up (relating to "serivces" [sic])

### ISSUE THREAD

**Issue by CecilWard** [colloquy/colloquy#3657]
How do I get rid of constant password prompts on startup? Don't know the answer, or what the password is for?

**Comment by zadr** [comment]
@CecilWard requests for "Services Password" are after we receive a 464 numeric from the server in response to a `PASS` sent with the wrong password, (464 IS `ERR_PASSWDMISMATCH` in RFC 1459, see: https://www.alien.net.au/irc/irc2numerics.html, so this is a reasonable thing for the server to send).

This numeric can also be sent by bouncers such as ZNC when you do not specify a password, or specify the wrong password.

```
	// :irc.znc.in 464 username :Password required // in the event that we do not send a PASS
	// :irc.znc.in 464 username :Invalid Password // in the event that we send the wrong PASS
```

**Comment by akempgen** [comment]
Services typo is fixed in c732a920baab2429e5fc7ff47b7de558d0920c45, thanks

**Comment by CecilWard** [comment]
How do i find out the password, set it, correct it - don't know where to look in the ui or what the procedure is?

**Comment by zadr** [comment]
The UI is the window that pops up asking you for the password. Enter the correct one in, and it will be saved. Enter the wrong password, or nothing, and it won’t be.

The UI is also the field that says “Server Password” when you go to manage the connection and edit it’s settings, same as when you made the connection in the first place.
