### ISSUE TITLE
In Colloquy Mobile, side bar is hidden

### ISSUE THREAD

**Issue by readingsnail** [colloquy/colloquy#3659]
![2e43db45-b764-4085-aafb-00a162b61fa9](https://user-images.githubusercontent.com/1904967/36472169-4d58b7cc-1734-11e8-8b93-a2c6d0935314.png)

So it’s normal,but other channel click

![1b8ab2a2-8dd4-4839-aa31-5109056d4ecc](https://user-images.githubusercontent.com/1904967/36472203-725c6df2-1734-11e8-976f-23e2dab6a191.png)

My connection list hidden(exactly, they move the top and even up the scroll, not show other connection / server. It’s repeat of change to channel) so this is very inconvenient. So may i pinned connect server / room?

Ana wow, it’s same of equal channel, using multitasking. yeah a channel show and turn thr safari etc, side bar is refresh and hidden

I using Mobile Colloquy 1.8.11 (6819) in landscape mode on an iPad running iOS Version 11.2.6 (Build 15D100)

**Comment by zadr** [comment]
fixed by 11118d8cb3534b795e190d67a624f916e035d89a, an update will be out soon!
