### ISSUE TITLE
Colloquy issue on 10.14 PB

### ISSUE THREAD

**Issue by readingsnail** [colloquy/colloquy#3669]
<img width="734" alt="2018-06-27 10 10 30" src="https://user-images.githubusercontent.com/1904967/41947397-5935ffac-79f2-11e8-8266-69fbda42b682.png">

in Tabbed states, it's broken. no chatting message, no tab.

<img width="780" alt="2018-06-27 10 18 40" src="https://user-images.githubusercontent.com/1904967/41947634-987e8caa-79f3-11e8-85d6-db5d5a00f99e.png">
also what is mic access on Colloquy? hide plan for voice chatting? or tapping? :D

affecting : Version 2.4.3 (6011), Version 2.5 (6917 - bouncer 98) + now Git version - yeah all broken. 🤔

**Comment by zadr** [comment]
@akempgen  fixed this in https://github.com/colloquy/colloquy/commit/69d4747a8fb9a0a18a96747687545dd278e43e02 and WebKit fixed the regression in https://trac.webkit.org/changeset/231456/webkit so future versions of both Colloquy and macOS will both fix the issue
