### ISSUE TITLE
now github version is not working commands

### ISSUE THREAD

**Issue by readingsnail** [colloquy/colloquy#3672]
well, so i compiled to current github version(Version 2.5 (6990), of course mac application checked) of colloquy. so today, i'm very damm experienced for this.

/nick is working, but /deop or /kick, /kick-ban is not working, only working GUI.

for now not working commands (Tested)
/op
/deop
/kick
/clear
/kickban (idk before i used chatzilla, they using /kick-ban. so two command input, but not working)

**Comment by zadr** [comment]
common /commands are provided as a plugin on macOS. If you build the `Colloquy (Aggregate)` target, they should be available
