### ISSUE TITLE
well, in Dark Mode, Colloquy is bad

### ISSUE THREAD

**Issue by readingsnail** [colloquy/colloquy#3683]
<img width="396" alt="2018-08-28 10 37 20" src="https://user-images.githubusercontent.com/1904967/44726551-f3a15e00-ab12-11e8-8d6b-a1e79b160f62.png">
<img width="396" alt="2018-08-28 10 37 16" src="https://user-images.githubusercontent.com/1904967/44726552-f439f480-ab12-11e8-94b9-64848996d83d.png">

i'm using dark mode, and some funny. better serious is Here
<img width="834" alt="2018-08-28 10 42 22" src="https://user-images.githubusercontent.com/1904967/44726870-a5408f00-ab13-11e8-81c1-afb2c459422d.png">

so i'm using 10.14 Beta 8(18A377a) and building currently version(some modified, but it's just strings. see my pull-request) & Xcode 10.0 beta 6 (10L232m)

**Comment by akempgen** [comment]
I can’t reproduce the dark about text, can you try again with the main branch without modifications and the latest Mojave?

The topic bar and the main chat view are known and I’m looking into what we can do there.

About the drawer ... don’t get your hopes up, it’s a deprecated component.

**Comment by readingsnail** [comment]
yeah drawer is not important - i know. problem is chat room is damm

<img width="836" alt="2018-08-29 5 42 13" src="https://user-images.githubusercontent.com/1904967/44776623-7843b900-abb3-11e8-9396-476a960aa602.png">
it's not modified string version(only using currently colloquy repo)

<img width="836" alt="2018-08-29 5 43 36" src="https://user-images.githubusercontent.com/1904967/44776633-7d086d00-abb3-11e8-9964-a580464307bf.png">
and it's yeah deleted application support folder -> rebuilding. so it's not concern application support folders.

a...nd my environment - Xcode / macOS
<img width="698" alt="2018-08-29 5 58 33" src="https://user-images.githubusercontent.com/1904967/44777317-49c6dd80-abb5-11e8-9bca-84e9294145f0.png">
<img width="642" alt="2018-08-29 5 58 26" src="https://user-images.githubusercontent.com/1904967/44777318-49c6dd80-abb5-11e8-893a-14f7fce48145.png">

**Comment by readingsnail** [comment]
ah, i found very weird things. so rollback to this version? so make writed reason for this. 6990 is not affected this.

<img width="396" alt="2018-09-01 12 47 44" src="https://user-images.githubusercontent.com/1904967/44942100-5762aa00-ade5-11e8-8192-8387b8f222e3.png">

<img width="1440" alt="2018-09-01 12 49 15" src="https://user-images.githubusercontent.com/1904967/44942106-74977880-ade5-11e8-83d0-f7505f060849.png">

**Comment by akempgen** [comment]
The input box is fixed in fefdd10
