### ISSUE TITLE
Mac App Store release or pre-built binaries

### ISSUE THREAD

**Issue by triplef** [colloquy/colloquy#3705]
It’d be great if Colloquy could be released on the Mac App Store in addition to the iOS app store, or if there could be pre-built binaries made available for macOS on the website for easy installation.

Thanks for your consideration!

**Comment by akempgen** [comment]
That would be great, but not possible at the moment. In the meantime you can get a build here on GitHub: https://github.com/colloquy/colloquy/releases/tag/mac%2F2020%2F2.5-prerelease-7051
