### ISSUE TITLE
SASL / libera.chat Incompatibility 

### ISSUE THREAD

**Issue by l008com** [colloquy/colloquy#3706]
I can't seem to successfully connect to libera.chat (the replacement to freenode.net). Site ops checked out my client (Colloquy) and said it's not using SASL like it should. 

I'm on 2.5 (7051)

**Comment by akempgen** [comment]
confirmed, colloquy doesn't properly handle the 3.2 sasl=... syntax here

`if( [capability isCaseInsensitiveEqualToString:@"sasl"] ` on line 2436 in `MVIRCChatConnection`.

https://ircv3.net/specs/extensions/capability-negotiation#capability-values
https://ircv3.net/specs/extensions/sasl-3.2

**Comment by akempgen** [comment]
Can you try with https://github.com/colloquy/colloquy/releases/tag/mac%2F2021%2F2.5-prerelease-7097 ?

**Comment by l008com** [comment]
It seems to work normally and connects to libera.chat fine. The only quirk I've noticed is that when I do a /me action, it double displays that in the chat window. Though others only see it once.
