### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by arjpar** [colloquy/colloquy#3711]
Last commit was in 2021, and seems like there isn't much activity.

**Comment by kenrachynski** [comment]
given the response to this issue, it sure looks like it.

I only started looking at it because somebody I know mentioned they tried a 2.x release and it wasn't actually working so they went back to a 1.9.x release to be able to use it on their Mac.

**Comment by xeenon** [comment]
Sadly, I would say it is. Colloquy had a good run, but I had to move on when I joined Apple 18 years ago.

**Comment by akempgen** [comment]
Latest build still works fine on Sonoma though 🙂 https://github.com/colloquy/colloquy/releases/tag/mac%2F2021%2F2.5-prerelease-7097
